# fly.toml app configuration file generated for noray on 2025-04-11T08:53:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'noray'
primary_region = 'ams'

[build]

[env]
  NORAY_SOCKET_HOST = "0.0.0.0"
  NORAY_HTTP_HOST = "0.0.0.0"
  NORAY_UDP_HOST = "0.0.0.0"

[http_service]
  internal_port = 8890
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[services]]
  protocol = "udp"
  internal_port = 8809
  
  [[services.ports]]
    port = 8809

[[services]]
  protocol = "tcp"
  internal_port = 8890
  
  [[services.ports]]
    port = 8890

[[services]]
  protocol = "tcp"
  internal_port = 8891
  
  [[services.ports]]
    port = 8891
